name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # AWS CLI를 위한 액세스 인증
      - name: 'Set up AWS CLI'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      # Bastion의 퍼블릭 IP 가져오기
      - name: 'Retrieve Bastion Public IP'
        id: get_bastion_ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name, Values=bastion" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "Bastion Public IP: $PUBLIC_IP"
          echo "BASTION_IP=$PUBLIC_IP" >> $GITHUB_ENV
      
      # Bastion에서 terraform destroy 실행
      - name: 'Install terrafrom on Bastion & clone tf file from git'
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/FPT2-key.pem ec2-user@${{ env.BASTION_IP }} << 'EOF'
            cd ~/Terraform-MR/terraform/aws
            terraform init
            terraform destroy -auto-approve
            exit
          EOF
      
      # Terraform 설치
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      # Terraform 초기화 
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform/local
      
      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform/local